### ISSUE TITLE
Setting Up Scenarios

### ISSUE THREAD

**Issue by kdorheim** [JGCRI/hectordata#2]
This is something that I've been wrestling with for a while now. For the CMIP6 scenarios do we want the scenarios to match the nomenclature of pervious Hector runs or the CMIP6 scenarios? 

If we take a look at the ini files in the Hector input. 
```
[1] "api-example.ini"                "constraints"                    "emissions"                     
 [4] "hector_rcp26_constrained.ini"   "hector_rcp26_histconstrain.ini" "hector_rcp26.ini"              
 [7] "hector_rcp45_constrained.ini"   "hector_rcp45.ini"               "hector_rcp60_constrained.ini"  
[10] "hector_rcp60.ini"               "hector_rcp85_constrained.ini"   "hector_rcp85.ini"              
[13] "hector-gcam.ini" 
```

The runs named `hector_rcp45.ini` use the scenario inputs from CMIP5 RCP 4.5 but the big difference is that in hector these are purely emission driven where as in CMIP5 these runs were driven with prescribed CO2 concentrations + emissions. 

So that being said for hectordata ini files do we want to set it up so that they are all purely emission driven like the runs or do we want them to match the CMIP definition of the scenarios? 

@bpbond I would be happy to hear your thoughts & the thoughts of others that want to weigh in. I am inclined to think that we should be consistent with how Hector does it but as a user that is also kind of a pain...

**Comment by bpbond** [comment]
That's an interesting question. You mean, should we have the ability to have emissions (as standard now) but also concentration (using the constraint capability) runs, matching CMIP definitions? Huh.

>"hector_rcp26_constrained.ini" "hector_rcp26_histconstrain.ini"

I.e. these are concentration and emission runs, respectively? I guess I'd say we don't need to match the _nomenclature_ of CMIP, but should (as you lay out above) match the _design_, i.e. provide files for both types of runs.

**Comment by kdorheim** [comment]
Yes right hector is set up so that `hector_rcp26_constrained.ini` is set up to actually match what the CMIP5 RCP26 run is. The hector_rcp26.ini` is an emissions driven run which was not done by any of the ESM models. 

We rely on the `*_constrained.ini` tag to indicate that the CO2 concentration is constrained. For the CMIP6 scenarios the majority of the runs use prescribed CO2 concentration, only three of them are actually emission driven. And then the idealized experiments are purely CO2 concentration driven. Do we want the idealized scenarios to look something like `picontrol_constrainted.ini`?

**Comment by bpbond** [comment]
Probably? I like keeping the nomenclature internally consistent.
